### ISSUE TITLE
which function is for for the standard deviation and posterior inclusion probability of the gene expression mediation effect size

### ISSUE THREAD

**Issue by yuanzhongshang** [YPARK/zqtl#5]
Hi,
I have successfully installed the zqtl package. I wonder which function is for the standard deviation and posterior inclusion probability of the gene expression mediation effect size.
Thanks a lot.
Bests,
zhongshang

**Comment by YPARK** [comment]
Sorry for the late response and thanks for the question.

I didn't make a separate function to access the results.  But I've tried to return as much results as list.

https://github.com/YPARK/zqtl/blob/be864b5e4fb2067adf5fb501ac259f6475ef419a/man/zqtl-med.Rd#L153

If you get an object (a list) `med.out` then you can access another list `param.mediated` then under that, you can find 

`lodds` : log odds ratio of PIP
`theta` : effect size (variational mean)
`theta.var` : variance

I don't have a good faith on `theta.var` since approximation of variance in the variational Bayes framework is not so great.
